name: Run qqemail.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: '05 23,6 * * *'  # 每天北京时间早上7点30分和中午2点30分执行

jobs:
  run_script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间
    
    steps:

    - name: Install dependencies
      run: pip install requests
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: python -m pip install requests
    - name: Install dependencies
      run: python -m pip install chardet

    - name: Run qqemail.py
      run: python qqemail.py
