name: Run qqemail.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: '05 23,6 * * *'  # 每天北京时间早上7点30分和中午2点30分执行

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Determine execution time
      id: execution_time
      run: |
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
          scheduled_time="${{ github.event.scheduled_time }}"
          # Convert scheduled_time to Beijing time (UTC+8)
          execution_time=$((scheduled_time + 8*3600))
          echo "Scheduled execution time (Beijing time): $(date -d @${execution_time})"
          echo "::set-output name=execution_time::${execution_time}"
        else
          # For push events, execute immediately
          execution_time=0
          echo "::set-output name=execution_time::${execution_time}"
        fi

    - name: Wait until execution time
      run: sleep $(( ${{ steps.execution_time.outputs.execution_time }} - $(date -u +%s) ))

    - name: Install dependencies
      run: pip install requests

    - name: Run qqemail.py
      run: python qqemail.py
